<a href="https://colab.research.google.com/github/yoonyoung27/public_big_data_analysis/blob/main/R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://colab.research.google.com/notebook#create=true&language=r

#ch02(연산자)

In [ ]:
500 + 300

[1] 800

In [ ]:
100^2 + 300

[1] 10300

In [ ]:
age <- 20
irum <- '지윤영'

In [ ]:
age

[1] 20

In [ ]:
irum

[1] "지윤영"

#ch03(함수)

In [ ]:
data()  # 내장 데이터 목록

In [ ]:
cars

speed dist
1   4      2 
2   4     10 
3   7      4 
4   7     22 
5   8     16 
6   9     10 
7  10     18 
8  10     26 
9  10     34 
10 11     17 
11 11     28 
12 12     14 
13 12     20 
14 12     24 
15 12     28 
16 13     26 
17 13     34 
18 13     34 
19 13     46 
20 14     26 
21 14     36 
22 14     60 
23 14     80 
24 15     20 
25 15     26 
26 15     54 
27 16     32 
28 16     40 
29 17     32 
30 17     40 
31 17     50 
32 18     42 
33 18     56 
34 18     76 
35 18     84 
36 19     36 
37 19     46 
38 19     68 
39 20     32 
40 20     48 
41 20     52 
42 20     56 
43 20     64 
44 22     66 
45 23     54 
46 24     70 
47 24     92 
48 24     93 
49 24    120 
50 25     85

In [ ]:
help(sum)

In [ ]:
?sum

In [ ]:
example(sum)


sum> ## Pass a vector to sum, and it will add the elements together.
sum> sum(1:5)
[1] 15

sum> ## Pass several numbers to sum, and it also adds the elements.
sum> sum(1, 2, 3, 4, 5)
[1] 15

sum> ## In fact, you can pass vectors into several arguments, and everything gets added.
sum> sum(1:2, 3:5)
[1] 15

sum> ## If there are missing values, the sum is unknown, i.e., also missing, ....
sum> sum(1:5, NA)
[1] NA

sum> ## ... unless  we exclude missing values explicitly:
sum> sum(1:5, NA, na.rm = TRUE)
[1] 15


#ch04(데이터_유형)

In [6]:
x <- 5
y <- 3.14

In [ ]:
x + y

[1] 8.14

In [ ]:
x > y

[1] TRUE

In [8]:
x = y
x == y

[1] TRUE

In [9]:
x <- x-3
x > y

[1] FALSE

In [4]:
Sys.Date()  # 현재 시각

[1] "2021-06-23"

In [2]:
d1 <- "2021-06-20"
as.Date(d1) + 100

[1] "2021-09-28"

In [3]:
height <- c(177,180,168,169,NA)
is.na(height[5])

[1] TRUE

In [ ]:
sum(height)

[1] NA

In [ ]:
rate <- NULL
money <- c(1200000, 950000, 1300000)
if(sum(money)>=3000000){
    rate<-0.017
}

is.null(rate)

[1] FALSE

#ch05(데이터\_구조\_유형)

##벡터

In [16]:
irums <- c('번개','미스터길동','도둑','활빈당')
irums

[1] "번개"       "미스터길동" "도둑"       "활빈당"

In [21]:
irums2 <- c('ㅂㄱ','ㅁㅅㅌㄱㄷ','ㄷㄷ','ㅎㅂㄷ')
c(irums, irums2)

[1] "번개"       "미스터길동" "도둑"       "활빈당"     "ㅂㄱ"      
[6] "ㅁㅅㅌㄱㄷ" "ㄷㄷ"       "ㅎㅂㄷ"

In [29]:
x <- -1:5
is.vector(x)

[1] TRUE

In [ ]:
seq(0,1000,200)

[1]    0  200  400  600  800 1000

In [ ]:
seq(0,1000,length=5)

[1]    0  250  500  750 1000

In [22]:
rep(1:5, times=2)

[1] 1 2 3 4 5 1 2 3 4 5

In [23]:
rep(1:5, each=2)

[1] 1 1 2 2 3 3 4 4 5 5

In [24]:
a <- vector(mode='numeric', length=20)
a  # 빈 벡터 생성

[1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [19]:
sample <- c(3000, 3500.12, 1500, 4200.7)
sample  # 실수로 인식

[1] 3000.00 3500.12 1500.00 4200.70

In [20]:
sample2 <- c(300, '한글', 14.5)
sample2  # 문자열로 인식

[1] "300"  "한글" "14.5"

In [ ]:
c <- as.character(x)
c

[1] "-1" "0"  "1"  "2"  "3"  "4"  "5"

In [ ]:
n <- as.numeric(c)
n

[1] -1  0  1  2  3  4  5

In [30]:
coffee <- c(3000,4500,4500,3500)
names(coffee) <- c('아메리카노','에스프레소','카페모카','화이트라뗴')
coffee

아메리카노 에스프레소   카페모카 화이트라뗴 
      3000       4500       4500       3500

In [31]:
coffee[3]

카페모카 
    4500

In [32]:
coffee['카페모카']

카페모카 
    4500

In [33]:
coffee[-3]

아메리카노 에스프레소 화이트라뗴 
      3000       4500       3500

In [34]:
coffee[3] <- 3000
coffee['카페모카']

카페모카 
    3000

In [35]:
coffee + 1000

아메리카노 에스프레소   카페모카 화이트라뗴 
      4000       5500       4000       4500

In [ ]:
x + 2

[1] 1 2 3 4 5 6 7

In [26]:
shop1 <- c(15,10,7,3)
shop2 <- c(20,10,3,8)
shop1 + shop2

[1] 35 20 10 11

In [ ]:
'헐크'%in%irums

[1] FALSE

In [ ]:
'도둑'%in%irums

[1] TRUE

In [ ]:
length(y)

[1] 6

In [ ]:
NROW(y)

[1] 6

In [ ]:
union(shop1, shop2)

[1] 15 10  7  3 20  8

In [ ]:
intersect(shop1, shop2)

[1] 10  3

In [ ]:
setdiff(shop1, shop2)

[1] 15  7

In [36]:
shop1 <- c(shop1, shop2)
shop2 <- c(shop2, shop1)
identical(shop1, shop2)

[1] FALSE

In [ ]:
setequal(shop1, shop2)

[1] TRUE

In [ ]:
pet <- factor(c('dog','dog','dog','cat','alligator'))
pet

[1] dog       dog       dog       cat       alligator
Levels: alligator cat dog

In [ ]:
religion <- factor(c('천주교','기독교','기독교','불교','불교','무교'), c('기독교','불교'))
religion

[1] <NA>   기독교 기독교 불교   불교   <NA>  
Levels: 기독교 불교

In [ ]:
width <- factor(c('18평','24평','24평','33평','33평','33평','18평'), ordered=TRUE)
width

[1] 18평 24평 24평 33평 33평 33평 18평
Levels: 18평 < 24평 < 33평

In [ ]:
table(religion)

religion
기독교   불교 
     2      2 

In [ ]:
unclass(width)

[1] 1 2 2 3 3 3 1
attr(,"levels")
[1] "18평" "24평" "33평"

##9

In [ ]:
my1 <- list("지윤영","대학생","서울",2.5)
my1

[[1]]
[1] "지윤영"

[[2]]
[1] "대학생"

[[3]]
[1] "서울"

[[4]]
[1] 2.5

In [ ]:
myfavorit <- list(friend=c'김지수',mynum=4,myalpha='w')
myfavorit

$friend
[1] "김지수"

$mynum
[1] 4

$myalpha
[1] "w"

In [ ]:
myfavorit$myalpha

[1] "w"

In [ ]:
myfavorit$mysong <- 'festa'
myfavorit

$friend
[1] "김지수"

$mynum
[1] 4

$myalpha
[1] "w"

$mysong
[1] "festa"

In [ ]:
myfavorit$friend <- c('김지수','류건욱')
myfavorit

$friend
[1] "김지수" "류건욱"

$mynum
[1] 4

$myalpha
[1] "w"

$mysong
[1] "festa"

In [ ]:
age <- matrix(c(25,33,32,37,27,38), nrow=2)
age

[,1] [,2] [,3]
[1,] 25   32   27  
[2,] 33   37   38

In [ ]:
age <- matrix(c(25,33,32,37,27,38), nrow=2, byrow=TRUE)
age

[,1] [,2] [,3]
[1,] 25   33   32  
[2,] 37   27   38

In [ ]:
info <- matrix(c('177cm','68kg','156cm','57kg','160cm','48kg','175kg','60kg'), ncol=2, byrow=TRUE)
info

[,1]  [,2]
[1,] 177cm 68kg
[2,] 156cm 57kg
[3,] 160cm 48kg
[4,] 175kg 60kg

In [ ]:
dimnames(info) <- list(c('1번','2번','3번','4번'), c('키','몸무게'))
info

키    몸무게
1번 177cm 68kg  
2번 156cm 57kg  
3번 160cm 48kg  
4번 175kg 60kg

In [ ]:
example(dimnames)


dimnms> ## simple versions of rownames and colnames
dimnms> ## could be defined as follows
dimnms> rownames0 <- function(x) dimnames(x)[[1]]

dimnms> colnames0 <- function(x) dimnames(x)[[2]]

dimnms> (dn <- dimnames(A <- provideDimnames(N <- array(1:24, dim = 2:4))))
[[1]]
[1] "A" "B"

[[2]]
[1] "A" "B" "C"

[[3]]
[1] "A" "B" "C" "D"


dimnms> A0 <- A; dimnames(A)[2:3] <- list(NULL)

dimnms> stopifnot(identical(A0, provideDimnames(A)))

dimnms> strd <- function(x) utils::str(dimnames(x))

dimnms> strd(provideDimnames(A, base= list(letters[-(1:9)], tail(LETTERS))))
List of 3
 $ : chr [1:2] "A" "B"
 $ : chr [1:3] "U" "V" "W"
 $ : chr [1:4] "j" "k" "l" "m"

dimnms> strd(provideDimnames(N, base= list(letters[-(1:9)], tail(LETTERS)))) # recycling
List of 3
 $ : chr [1:2] "j" "k"
 $ : chr [1:3] "U" "V" "W"
 $ : chr [1:4] "j" "k" "l" "m"

dimnms> strd(provideDimnames(A, base= list(c("AA","BB")))) # recycling on both levels
List of 3
 $ : chr [1:2] "A" "B"
 $ : chr [1:3] "AA" "BB" "AA1"
 $ :

In [ ]:
info <- cbind(info, c('남','남','여','여'))
info

키    몸무게   
1번 177cm 68kg   남
2번 156cm 57kg   남
3번 160cm 48kg   여
4번 175kg 60kg   여

In [ ]:
a1 <- c('180cm','70kg','남')
a2 <- c('185cm','68kg','남')
rbind(info, a1, a2)

키    몸무게   
1번 177cm 68kg   남
2번 156cm 57kg   남
3번 160cm 48kg   여
4번 175kg 60kg   여
a1  180cm 70kg   남
a2  185cm 68kg   남

In [ ]:
dimnames(info) <- list(c('1번','2번','3번','4번'), c('키','몸무게', '성별'))
info

키    몸무게 성별
1번 177cm 68kg   남  
2번 156cm 57kg   남  
3번 160cm 48kg   여  
4번 175kg 60kg   여

In [ ]:
df <- data.frame(irum=c('조정순','한민애','고승민'), age=c(43,27,34))
df

irum   age
1 조정순 43 
2 한민애 27 
3 고승민 34

In [ ]:
irum <- c('조정순','한민애','고승민')
age <- c(43,27,34)
df2 <- data.frame(이름=irum,나이=age)
df2

이름   나이
1 조정순 43  
2 한민애 27  
3 고승민 34

In [ ]:
df2$이름

[1] "조정순" "한민애" "고승민"

In [ ]:
df2$나이 + 1

[1] 44 28 35

In [ ]:
carinfo <- matrix(c('11km','13km','10km','h사','p사','r사'), ncol=2)
dfr <- as.data.frame(carinfo)
dfr

V1   V2 
1 11km h사
2 13km p사
3 10km r사

In [ ]:
names(dfr) <- c('연비','제조사')
dfr

연비 제조사
1 11km h사   
2 13km p사   
3 10km r사

In [ ]:
getwd()

[1] "/content"

In [ ]:
pinfo <- read.table("/content/personal.txt", header=TRUE, fileEncoding = "EUC-KR")  # 한글로 된 내용이 있는 경우
pinfo

이름   거주지역 나이 성별
1 홍민수 인천     25   남  
2 조정란 경기     33   여  
3 국정수 서울     43   남  
4 라윤정 서울     35   여  
5 한주연 인천     37   남

In [ ]:
system('gdown --id 1kVXF9gVuJ2EmT6XTAyYr5z50y4wDwQOF')
pinfo <- read.table("personal.txt", header=TRUE, fileEncoding = "EUC-KR")
pinfo

이름   거주지역 나이 성별
1 홍민수 인천     25   남  
2 조정란 경기     33   여  
3 국정수 서울     43   남  
4 라윤정 서울     35   여  
5 한주연 인천     37   남

In [ ]:
system('gdown --id 1hq0Pxy5JtbVCgn6wsY0Z4uVSuPA329EL')
pjobinfo <- read.table("pjob.txt", header=TRUE, fileEncoding = "EUC-KR")
pjobinfo

이름   직업    
1 홍민수 학생    
2 조정란 공무원  
3 박장곤 회사원  
4 한지수 자영업  
5 한주연 프리랜서
6 주민정 학생

In [ ]:
lifeinfo <- data.frame(취미 = c('목공예','패러글라이딩','등산','꽃꽃이','독서'), 관심사 = c('취업','아파트분양','주택대출','이직','교통인프라'))
lifeinfo

취미         관심사    
1 목공예       취업      
2 패러글라이딩 아파트분양
3 등산         주택대출  
4 꽃꽃이       이직      
5 독서         교통인프라

In [ ]:
myinfo <- cbind(pinfo, lifeinfo)
myinfo

이름   거주지역 나이 성별 취미         관심사    
1 홍민수 인천     25   남   목공예       취업      
2 조정란 경기     33   여   패러글라이딩 아파트분양
3 국정수 서울     43   남   등산         주택대출  
4 라윤정 서울     35   여   꽃꽃이       이직      
5 한주연 인천     37   남   독서         교통인프라

In [ ]:
otherinfo <- data.frame(이름 = c('황성주','윤준영'), 거주지역 = c('강원','충북'), 나이 = c(42, 45), 성별 = c('여','여'))
otherinfo

이름   거주지역 나이 성별
1 황성주 강원     42   여  
2 윤준영 충북     45   여

In [ ]:
totinfo <- rbind(pinfo, otherinfo)
totinfo

이름   거주지역 나이 성별
1 홍민수 인천     25   남  
2 조정란 경기     33   여  
3 국정수 서울     43   남  
4 라윤정 서울     35   여  
5 한주연 인천     37   남  
6 황성주 강원     42   여  
7 윤준영 충북     45   여

In [ ]:
merge(pinfo, pjobinfo)

이름   거주지역 나이 성별 직업    
1 조정란 경기     33   여   공무원  
2 한주연 인천     37   남   프리랜서
3 홍민수 인천     25   남   학생

In [ ]:
merge(pinfo, pjobinfo, all=TRUE)

이름   거주지역 나이 성별 직업    
1 국정수 서울     43   남   NA      
2 라윤정 서울     35   여   NA      
3 박장곤 NA       NA   NA   회사원  
4 조정란 경기     33   여   공무원  
5 주민정 NA       NA   NA   학생    
6 한주연 인천     37   남   프리랜서
7 한지수 NA       NA   NA   자영업  
8 홍민수 인천     25   남   학생

In [ ]:
data1 <- subset(pinfo, select=-거주지역)
data1

이름   나이 성별
1 홍민수 25   남  
2 조정란 33   여  
3 국정수 43   남  
4 라윤정 35   여  
5 한주연 37   남

In [ ]:
data2 <- cbind(pinfo, 결혼=c(FALSE, TRUE, TRUE, FALSE, TRUE))
data2

이름   거주지역 나이 성별 결혼 
1 홍민수 인천     25   남   FALSE
2 조정란 경기     33   여    TRUE
3 국정수 서울     43   남    TRUE
4 라윤정 서울     35   여   FALSE
5 한주연 인천     37   남    TRUE

In [ ]:
data2[-3,]

이름   거주지역 나이 성별 결혼 
1 홍민수 인천     25   남   FALSE
2 조정란 경기     33   여    TRUE
4 라윤정 서울     35   여   FALSE
5 한주연 인천     37   남    TRUE

In [ ]:
data2[,-5]

이름   거주지역 나이 성별
1 홍민수 인천     25   남  
2 조정란 경기     33   여  
3 국정수 서울     43   남  
4 라윤정 서울     35   여  
5 한주연 인천     37   남

In [ ]:
ncol(data2)

[1] 5

In [ ]:
nrow(data2)

[1] 5

In [ ]:
colnames(data2) <- c('성명','거주지','나이','성별')
data2

성명   거주지 나이 성별 <NA> 
1 홍민수 인천   25   남   FALSE
2 조정란 경기   33   여    TRUE
3 국정수 서울   43   남    TRUE
4 라윤정 서울   35   여   FALSE
5 한주연 인천   37   남    TRUE

#조건문

In [ ]:
a <- 8
if(a%%2 == 0){
    result <- '짝수'
    result
}

[1] "짝수"

In [ ]:
a <- 123
if(a%%2 == 0){
    result <- '짝수'
}else{
    result <- '홀수'
}
result

[1] "홀수"

In [ ]:
a <- 75
if(a%%3 == 0 && a%%5 == 0){
    result <- '3의 배수이면서 5의 배수'
}else if(a%%3 == 0){
    result <- '3의 배수'
}else if(a%%5 == 0){
    result <- '5의 배수'
}else{
    result <- '3의 배수, 5의 배수 어디에도 해당되지 않습니다'
}
result

[1] "3의 배수이면서 5의 배수"

In [ ]:
a <- c(10,13,7,8,50)
if(a%%2==0){
    result<-'짝수'
}else{
    result<-'홀수'
}
result

Warning message in if (a%%2 == 0) {:
“the condition has length > 1 and only the first element will be used”


[1] "짝수"

In [ ]:
a <- c(10,13,7,8,50)
result <- c(ifelse(a%%2==0, '짝수', '홀수'))

df <- data.frame(a, result)
df

a  result
1 10 짝수  
2 13 홀수  
3  7 홀수  
4  8 짝수  
5 50 짝수

In [ ]:
a <- c(10,13,22,15,9)
result <- ifelse(a>mean(a), '평균초과', ifelse(a<mean(a), '평균미달', '평균값'))

df2 <- data.frame(a, result)
df2

a  result  
1 10 평균미달
2 13 평균미달
3 22 평균초과
4 15 평균초과
5  9 평균미달

#반복문

In [ ]:
y <- 0
for(x in 1:5){
    y <- y+x
    cat('1부터',x,'까지 합은 ', y, '\n')
}
y

1부터 1 까지 합은  1 
1부터 2 까지 합은  3 
1부터 3 까지 합은  6 
1부터 4 까지 합은  10 
1부터 5 까지 합은  15 


[1] 15

In [ ]:
a <- c(4,25,8,33,17,20)
evensum <- 0
for(x in a){
    if(x%%2==0) evensum <- evensum+x
}
#for(x in 1:length(a)){
#    if (a[x]%%2==0) evensum <- evensum+x
#} 과 같은 의미
evensum

[1] 32

In [ ]:
gugudan <- matrix(0, nrow=9, ncol=9)
for(i in 1:9){
    for (j in 1:9){
        gugudan[i,j] <- i*j
    }
}
gugudan

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
 [1,] 1     2    3    4    5    6    7    8    9  
 [2,] 2     4    6    8   10   12   14   16   18  
 [3,] 3     6    9   12   15   18   21   24   27  
 [4,] 4     8   12   16   20   24   28   32   36  
 [5,] 5    10   15   20   25   30   35   40   45  
 [6,] 6    12   18   24   30   36   42   48   54  
 [7,] 7    14   21   28   35   42   49   56   63  
 [8,] 8    16   24   32   40   48   56   64   72  
 [9,] 9    18   27   36   45   54   63   72   81

In [ ]:
i <- 1
isum <- 0
while(i<=10){
    isum <- isum+i
    i <- i+1
}
isum

[1] 55

In [ ]:
i <- 1
isum <- 0
while(i != 0){
    isum <- isum + i
    cat('1부터', i, '까지 합은 ', isum, '\n')
    if(isum>500) break
    i <- i+1
}

1부터 1 까지 합은  1 
1부터 2 까지 합은  3 
1부터 3 까지 합은  6 
1부터 4 까지 합은  10 
1부터 5 까지 합은  15 
1부터 6 까지 합은  21 
1부터 7 까지 합은  28 
1부터 8 까지 합은  36 
1부터 9 까지 합은  45 
1부터 10 까지 합은  55 
1부터 11 까지 합은  66 
1부터 12 까지 합은  78 
1부터 13 까지 합은  91 
1부터 14 까지 합은  105 
1부터 15 까지 합은  120 
1부터 16 까지 합은  136 
1부터 17 까지 합은  153 
1부터 18 까지 합은  171 
1부터 19 까지 합은  190 
1부터 20 까지 합은  210 
1부터 21 까지 합은  231 
1부터 22 까지 합은  253 
1부터 23 까지 합은  276 
1부터 24 까지 합은  300 
1부터 25 까지 합은  325 
1부터 26 까지 합은  351 
1부터 27 까지 합은  378 
1부터 28 까지 합은  406 
1부터 29 까지 합은  435 
1부터 30 까지 합은  465 
1부터 31 까지 합은  496 
1부터 32 까지 합은  528 


In [ ]:
a <- c(42,25,16,7,23,12,9)
i <- 1
repeat{
    if(a[i]<mean(a)) break
    i <- i+1
}

mean(a)
a[i]

[1] 19.14286

[1] 16

#함수

#패키지

In [10]:
install.packages('ggplot2')

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [11]:
library(ggplot2)

In [12]:
installed.packages()  # 설치된 패키지 목록

Package     LibPath                       Version  Priority   
ggplot2     ggplot2     /usr/local/lib/R/site-library 3.3.4    NA         
IRdisplay   IRdisplay   /usr/local/lib/R/site-library 1.0      NA         
IRkernel    IRkernel    /usr/local/lib/R/site-library 1.2      NA         
pbdZMQ      pbdZMQ      /usr/local/lib/R/site-library 0.3-5    NA         
repr        repr        /usr/local/lib/R/site-library 1.1.3    NA         
askpass     askpass     /usr/lib/R/site-library       1.1      NA         
assertthat  assertthat  /usr/lib/R/site-library       0.2.1    NA         
backports   backports   /usr/lib/R/site-library       1.2.1    NA         
base64enc   base64enc   /usr/lib/R/site-library       0.1-3    NA         
BH          BH          /usr/lib/R/site-library       1.75.0-0 NA         
blob        blob        /usr/lib/R/site-library       1.2.1    NA         
brew        brew        /usr/lib/R/site-library       1.0-6    NA         
brio        brio        /usr/lib/R/site-library       1.1.2    NA         
broom       broom       /usr/lib/R/site-library       0.7.6    NA         
cachem      cachem      /usr/lib/R/site-library       1.0.5    NA         
callr       callr       /usr/lib/R/site-library       3.7.0    NA         
cellranger  cellranger  /usr/lib/R/site-library       1.1.0    NA         
cli         cli         /usr/lib/R/site-library       2.5.0    NA         
clipr       clipr       /usr/lib/R/site-library       0.7.1    NA         
colorspace  colorspace  /usr/lib/R/site-library       2.0-1    NA         
commonmark  commonmark  /usr/lib/R/site-library       1.7      NA         
cpp11       cpp11       /usr/lib/R/site-library       0.2.7    NA         
crayon      crayon      /usr/lib/R/site-library       1.4.1    NA         
credentials credentials /usr/lib/R/site-library       1.3.0    NA         
curl        curl        /usr/lib/R/site-library       4.3.1    NA         
data.table  data.table  /usr/lib/R/site-library       1.14.0   NA         
DBI         DBI         /usr/lib/R/site-library       1.1.1    NA         
dbplyr      dbplyr      /usr/lib/R/site-library       2.1.1    NA         
desc        desc        /usr/lib/R/site-library       1.3.0    NA         
devtools    devtools    /usr/lib/R/site-library       2.4.2    NA         
⋮           ⋮           ⋮                             ⋮        ⋮          
zip         zip         /usr/lib/R/site-library       2.2.0    NA         
base        base        /usr/lib/R/library            4.1.0    base       
boot        boot        /usr/lib/R/library            1.3-28   recommended
class       class       /usr/lib/R/library            7.3-19   recommended
cluster     cluster     /usr/lib/R/library            2.1.2    recommended
codetools   codetools   /usr/lib/R/library            0.2-18   recommended
compiler    compiler    /usr/lib/R/library            4.1.0    base       
datasets    datasets    /usr/lib/R/library            4.1.0    base       
foreign     foreign     /usr/lib/R/library            0.8-81   recommended
graphics    graphics    /usr/lib/R/library            4.1.0    base       
grDevices   grDevices   /usr/lib/R/library            4.1.0    base       
grid        grid        /usr/lib/R/library            4.1.0    base       
KernSmooth  KernSmooth  /usr/lib/R/library            2.23-20  recommended
lattice     lattice     /usr/lib/R/library            0.20-44  recommended
MASS        MASS        /usr/lib/R/library            7.3-54   recommended
Matrix      Matrix      /usr/lib/R/library            1.3-4    recommended
methods     methods     /usr/lib/R/library            4.1.0    base       
mgcv        mgcv        /usr/lib/R/library            1.8-36   recommended
nlme        nlme        /usr/lib/R/library            3.1-152  recommended
nnet        nnet        /usr/lib/R/library            7.3-16   recommended
parallel    parallel    /usr/lib/R/library            4.1.0    base       
rpart       rpart       /usr/lib/R/li

In [13]:
update.packages('ggplot2')

In [14]:
remove.packages('ggplot2')

Removing package from ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

